version: "2"

networks:
  web:
    driver: bridge

services:
    api:
        build:
           context: .
           dockerfile: api
        ports:
           - "8001:80"
        volumes:
           - /home/docker/api/www:/var/www/
           - /home/docker/api/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
           - db_api
        networks:
           - web

    db_api:
        image: mariadb:10.2.18
        ports:
            - "3307:3306"
        networks:
            - web
        volumes:
            - /home/docker/api/db:/var/lib/mysqld:rw
        environment:
            - MYSQL_ROOT_PASSWORD=55dfc8690afade73f9a156ca3f8aa74e
            - MYSQL_DATABASE=api
            - MYSQL_USER=api
            - MYSQL_PASSWORD=9ca10ebf69289f3e2ea3db024408c92b

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        networks:
            - web
        depends_on:
            - db_api
        ports:
            - "8000:80"
        environment:
            - MYSQL_USER=api
            - MYSQL_PASSWORD=9ca10ebf69289f3e2ea3db024408c92b
            - MYSQL_ROOT_PASSWORD=55dfc8690afade73f9a156ca3f8aa74e
            - PMA_HOST=db_api

